from enum import Enum, auto


class SituationCode(str, Enum):
    NORMAL = "NORMAL"
    S1 = "S1"
    S2 = "S2"
    S3 = "S3"
    S4 = "S4"
    S5 = "S5"


class ActionMode(str, Enum):
    FOLLOW_NOMINAL = "FOLLOW_NOMINAL"
    WAIT = "WAIT"
    STOP = "STOP"
    DELAY_ENTRY = "DELAY_ENTRY"
    AVOID = "AVOID"


class StepId(str, Enum):
    STEP1_APPROACH_BOX_PICK = "STEP1_APPROACH_BOX_PICK"
    STEP1_GRASP = "STEP1_GRASP"
    STEP1_LIFT = "STEP1_LIFT"
    STEP2_TRANSFER_HOLDER = "STEP2_TRANSFER_HOLDER"
    STEP2_PLACE_HOLDER = "STEP2_PLACE_HOLDER"
    STEP2_RETREAT = "STEP2_RETREAT"
    STEP3_APPROACH_HOLDER_PICK = "STEP3_APPROACH_HOLDER_PICK"
    STEP3_GRASP = "STEP3_GRASP"
    STEP3_LIFT = "STEP3_LIFT"
    STEP4_TRANSFER_BOX2 = "STEP4_TRANSFER_BOX2"
    STEP4_PLACE_BOX2 = "STEP4_PLACE_BOX2"
    STEP4_RETREAT_FINISH = "STEP4_RETREAT_FINISH"


class StepPhase(str, Enum):
    MOTION = "MOTION"
    GRIPPER = "GRIPPER"
    HOLD = "HOLD"